export const OPEN_DISCLOSURE = 'AGGREGATOR_OPEN_DISCLOSURE';
export const CLOSE_DISCLOSURE = 'AGGREGATOR_CLOSE_DISCLOSURE';
export const RESET = 'AGGREGATOR_RESET';
export const SET_FOCUS = 'SET_FOCUS';

